/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { Share, shareBeet } from '../types/Share'
import {
  BondingCurveMode,
  bondingCurveModeBeet,
} from '../types/BondingCurveMode'

/**
 * Arguments used to create {@link PersonalMarket}
 * @category Accounts
 * @category generated
 */
export type PersonalMarketArgs = {
  id: beet.bignum
  holders: Share[]
  marketCurrency: web3.PublicKey
  totalShares: beet.bignum
  totalTrades: beet.bignum
  totalVolume: beet.bignum
  mode: BondingCurveMode
  currentPurchasePrice: beet.bignum
  currentSalePrice: beet.bignum
}

export const personalMarketDiscriminator = [163, 78, 142, 182, 232, 92, 26, 221]
/**
 * Holds the data for the {@link PersonalMarket} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class PersonalMarket implements PersonalMarketArgs {
  private constructor(
    readonly id: beet.bignum,
    readonly holders: Share[],
    readonly marketCurrency: web3.PublicKey,
    readonly totalShares: beet.bignum,
    readonly totalTrades: beet.bignum,
    readonly totalVolume: beet.bignum,
    readonly mode: BondingCurveMode,
    readonly currentPurchasePrice: beet.bignum,
    readonly currentSalePrice: beet.bignum
  ) {}

  /**
   * Creates a {@link PersonalMarket} instance from the provided args.
   */
  static fromArgs(args: PersonalMarketArgs) {
    return new PersonalMarket(
      args.id,
      args.holders,
      args.marketCurrency,
      args.totalShares,
      args.totalTrades,
      args.totalVolume,
      args.mode,
      args.currentPurchasePrice,
      args.currentSalePrice
    )
  }

  /**
   * Deserializes the {@link PersonalMarket} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [PersonalMarket, number] {
    return PersonalMarket.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link PersonalMarket} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<PersonalMarket> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find PersonalMarket account at ${address}`)
    }
    return PersonalMarket.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'EXSphcPS7fXSnmVPqo8Q5Hax5yRnc3t4MFWD1NozvMro'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, personalMarketBeet)
  }

  /**
   * Deserializes the {@link PersonalMarket} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [PersonalMarket, number] {
    return personalMarketBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link PersonalMarket} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return personalMarketBeet.serialize({
      accountDiscriminator: personalMarketDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link PersonalMarket} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: PersonalMarketArgs) {
    const instance = PersonalMarket.fromArgs(args)
    return personalMarketBeet.toFixedFromValue({
      accountDiscriminator: personalMarketDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link PersonalMarket} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: PersonalMarketArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      PersonalMarket.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link PersonalMarket} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      id: (() => {
        const x = <{ toNumber: () => number }>this.id
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      holders: this.holders,
      marketCurrency: this.marketCurrency.toBase58(),
      totalShares: (() => {
        const x = <{ toNumber: () => number }>this.totalShares
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      totalTrades: (() => {
        const x = <{ toNumber: () => number }>this.totalTrades
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      totalVolume: (() => {
        const x = <{ toNumber: () => number }>this.totalVolume
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      mode: 'BondingCurveMode.' + BondingCurveMode[this.mode],
      currentPurchasePrice: (() => {
        const x = <{ toNumber: () => number }>this.currentPurchasePrice
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      currentSalePrice: (() => {
        const x = <{ toNumber: () => number }>this.currentSalePrice
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const personalMarketBeet = new beet.FixableBeetStruct<
  PersonalMarket,
  PersonalMarketArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['id', beet.u64],
    ['holders', beet.array(shareBeet)],
    ['marketCurrency', beetSolana.publicKey],
    ['totalShares', beet.u64],
    ['totalTrades', beet.u64],
    ['totalVolume', beet.u64],
    ['mode', bondingCurveModeBeet],
    ['currentPurchasePrice', beet.u64],
    ['currentSalePrice', beet.u64],
  ],
  PersonalMarket.fromArgs,
  'PersonalMarket'
)
