/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type Share = {
  user: web3.PublicKey
  market: web3.PublicKey
  owned: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const shareBeet = new beet.BeetArgsStruct<Share>(
  [
    ['user', beetSolana.publicKey],
    ['market', beetSolana.publicKey],
    ['owned', beet.u64],
  ],
  'Share'
)
